const Strings = {
    step: 'Step',
    areYouSure: 'Are you sure you want to remove?',
    yes: 'Yes',
    no: 'No',
    logoutTitle: 'Log out your account?',

    confirmNewPassword: 'Confirm New Password',
    password:'password',
    addCorrectPassword:'Please add correct password.',
    addOldPassword: 'Please add old password.',
    addNewPassword: 'Please add new password.',
    addCorrectEmail: 'Please add correct email.',
    addConfirmPassword:'Please add confirm password.',
    passwordMissmatch: 'Password is mismatch.',
    updatePassword:'Update your password',
    DomainANumber: 'Domain a Number',
    DomainANumberText: 'Please select how many domains you want to display in the game.',
    update:'Update',
    editProfile: 'Edit Profile',
    name: 'Name',
    email: 'Email',
    password:'Password',
    savedDomain: 'My Saved Domains',
    modalClosed: 'Modal has been closed.',
    verifyEmail:'Enter it below to verify this email ',
    testEmail: 'm-mustaqeem@outlook.com',
    otp: 'OTP',
    emailSend:'Email Send',
    weHaveSentEmail: 'We’ve sent an email to your email address. Follow the steps provided in the email to update your password.',
    enterYourEmail: 'Enter your email address and select send email',
    setNewPassword:'Set New password',
    sendEmail: 'Send Email',
    isItSnagged: 'Is it Snagged?',
    whichDomainNotTaken: 'Which of the following domain is not taken.',
    playAgain: 'Play Again',
    show: 'Show',
    gameSettings: 'Game Setting',
    presetModes: 'Pre-set modes',
    DomainNumber: 'Domain Number',
    ShowingTLD:'Showing TLD',
    hi:'Hi, ',
    testName:'Jack',
    letsPlay: 'Let’s Play',
    startGame: 'Start Game',
    howItWork: 'How it work?',
    login: 'Login',
    letsGetStarted: 'Let’s get started. How do you identify?',
    forgotPassword: 'Forgot Password ?',
    doNothaveAccount: 'Do not have an account? ',
    signup: 'Signup',
    signUP: 'Sign Up',
    privacyPolicyText: 'By registering, you agree to our Terms of Service and our Privacy Policy',
    Custom: 'Custom',
    TLDSelect: 'Select a TLD',
    readyToPlay: 'Are you Ready to Play?',
    enterCustomDomain: 'Enter Custom Domain Name',
    selectPresetMode: 'Please select your pre-set mode.',
    selectHowManyDomains: 'Please select how many domains you want to display in the game.',
    selectTopLevelDomain: 'Please select which Top-level domains you want to display in the game.',
    favoriteOrPurchaseDomains:'Can you guess which one has not already been taken? You have the opportunity to favorite or even purchase available domains to add to your collection.',
    writeHere: 'Write here...',
    happySnagging: 'Happy Snagging!',
    enterYourCustomWords: 'Enter your custom words or phrases to you want to include in the domain.',
    settings:'Settings',
    enterName: 'Please enter name',
    enterEmail: 'Please enter email',
    enterPassword: 'Please enter password',
    enterConfirmPassword: 'Please enter confirm password',
    passwordAndConfirmPassword: 'Password and confirm password must be same',
    alreadyHaveAcc:'Already have an account?',
    dashboard: 'Dashboard'
  };
  
  export default Strings;
  